version: "3.3"

services:

  web:
    container_name: web_service
    build: .
    command: uvicorn src.main:app
      --reload
      --host $CONTAINER_HOST
      --port $CONTAINER_PORT
      --ssl-keyfile=$SSL_KEY_FILE
      --ssl-certfile=$SSL_CERT_FILE
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "$HOST_PORT:$CONTAINER_PORT"

  db:
    container_name: $DB_CONTAINER_NAME
    image: mongo:latest
    volumes:
      - ${MONGO_DATA_DIR}:/data/db/
