version: "3.3"

services:
  web:
    build: .
    command: uvicorn src.main:app
      --reload
      --host $CONTAINER_HOST
      --port $CONTAINER_PORT
    volumes:
      - .:/app
    ports:
      - "$HOST_PORT:$CONTAINER_PORT"
