version: "3.3"

services:
  web:
    build: .
    command: uvicorn src.main:app
      --reload
      --host $CONTAINER_HOST
      --port $CONTAINER_PORT
      --ssl-keyfile=$SSL_KEY_FILE
      --ssl-certfile=$SSL_CERT_FILE
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "$HOST_PORT:$CONTAINER_PORT"
