version: "3.3"

services:

  web:
    container_name: web_service
    build:
      dockerfile: ./Dockerfile.dev
      context: .
    command: uvicorn src.main:app
      --reload
      --host $CONTAINER_HOST
      --port $CONTAINER_PORT
    ports:
      - "$HOST_PORT:$CONTAINER_PORT"

  db:
    container_name: $DB_CONTAINER_NAME
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
    - ${MONGO_DATA_DIR}:/data/db/